server:
  port: 7003
  servlet:
    context-path: /uaa
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: cxtx-uaa
  cloud:
    nacos: #配置注册中心
      discovery:
        server-addr: 192.168.1.15:8848

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.117.128.180:3306/boot_c?serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=true&allowMultiQueries=true
    username: bootc
    password: 12345678